### ISSUE TITLE
Could you please attach a license file?

### ISSUE THREAD

**Issue by yca-estos** [ok2c/httpclient-android-ext#2]
Without any license file, according to Github default license policy, no one is allowed to use this code.

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository
`You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The Open Source Guide provides additional guidance on choosing the correct license for your project.`

**Comment by ok2c** [comment]
@yca-estos My bad. Will do this week.

**Comment by ok2c** [comment]
@yca-estos Done. Please verify.

**Comment by yca-estos** [comment]
License and Notice files are attached.
Perfect. Thanks a lot...
