### ISSUE TITLE
NTLM auth is failing while processing 2nd challenge response

### ISSUE THREAD

**Issue by yca-estos** [ok2c/httpclient-android-ext#3]
in file NTLMScheme.java (line 103), ntlm authenticator is trying to read value field (authChallenge.getValue()) but it is null.
challange parameters are stored in AuthChallange.params field.
<img width="941" alt="Screen Shot 2022-01-23 at 20 21 20" src="https://user-images.githubusercontent.com/91329898/150694519-4216bb91-ad43-40d1-ba8e-1818af685560.png">

**Comment by ok2c** [comment]
@yca-estos Screenshots are not very useful in bug reports. 
1. Please provide the _exact_ exception stack trace thrown.
2. Please mention the _exact_version of Apache HttpClient you are using.
3. Please provide a reproducer in a form a test case or sequence steps to be taken to trigger the reported defect.

**Comment by yca-estos** [comment]
1. For this ntlm issue, there is no exception but I can share log files.
Inside "NoRequestAfter2ndResponse.txt", there is an outgoing GET request and then a response with header => Www-Authenticate: NTLM
Then 2nd GET request is executed with Authorization header and then a new challenge is received with header => Www-Authenticate: NTLM TlRMTVNTUAACAAAAAAAAACgAAAABAAAAAAAAAAAAAAA=
And then, in the end of the logs, we see message "Authentication failed"
There should be one more HTTP GET request to complete authentication.
[NoRequestAfter2ndResponse.txt](https://github.com/ok2c/httpclient-android-ext/files/7924666/NoRequestAfter2ndResponse.txt)
Here is another log with an external Authenticator (which process NTLM challenge properly)
[RequestAfter2ndResponse.txt](https://github.com/ok2c/httpclient-android-ext/files/7924737/RequestAfter2ndResponse.txt)


2. version used: 0.1.1

3. sample code to reproduce issue (only 2 GET requests executed)
```
            val credentialStore: CredentialsStore = BasicCredentialsProvider()
            credentialStore.setCredentials(
                    AuthScope(null, null, -1, null, "NTLM"),
                    NTCredentials("test", "test".toCharArray(), null, null))

            val httpClient = HttpClients.custom()
                    .setDefaultCredentialsProvider(credentialStore)
                    .build()

            val request = HttpGet("http://ntlm.herokuapp.com/")
            request.config = RequestConfig.custom().setTargetPreferredAuthSchemes(listOf("NTLM")).setAuthenticationEnabled(true).build()
            var response: CloseableHttpResponse? = null
            try {
                response = httpClient.execute(request)
            } catch (e: Exception) {
                e.printStackTrace()
            }
            response?.close()
            httpClient.close()
```

**Comment by ok2c** [comment]
@yca-estos Please upgrade to Apache HttpClient 5.1.2 and re-test. If the problem still persists please let me know.

**Comment by yca-estos** [comment]
Actually I don't have any dependency for Apache HttpClient in my project.
I only have dependency for "httpclient-android" library.

```
dependencies {
........
    implementation 'com.github.ok2c.hc5.android:httpclient-android:0.1.1'
........
}

```
Do I have chance to update Apache HttpClient version in that case?

NOTE: Screenshot for NTLMScheme.java is taken from cached code inside "httpclient-android" library while debugging.
I don't have any other NTLMScheme.java code inside my project

**Comment by ok2c** [comment]
> Actually I don't have any dependency for Apache HttpClient in my project.

You do, but it is a transitive dependency. You can make it a direct dependency with the latest release version.

```
dependencies {
    implementation 'org.apache.httpcomponents.client5:httpclient5:5.1.2'
}

**Comment by ok2c** [comment]
@yca-estos The latest snapshots of Apache HttpClient also exhibit the same behavior. Please raise this issue in Apache JIRA https://issues.apache.org/jira/projects/HTTPCLIENT/

**Comment by yca-estos** [comment]
ok, I created a ticket there: https://issues.apache.org/jira/browse/HTTPCLIENT-2199
thanks...

**Comment by ok2c** [comment]
@yca-estos I am confused. You have raised a completely different issue with the Apache project.

**Comment by yca-estos** [comment]
let me copy my first comment then.

NOTE: btw the issue is => challenge is read from "value" field instead of "params" in NTLMScheme.java file (as in screenshot)
I wrote an external auth scheme for ntlm (using existing NTLMScheme.java file) and fixed it that way in my project.

**Comment by yca-estos** [comment]
ok i copied my second comment here into jira task (and updated title). is that ok?
